# R/plotting.R
library(ggplot2)
library(pROC)

#' Plot Multi-class ROC Curves
#' @param roc_list A list of ROC objects generated by calculate_ovr_roc
#' @param model_name A string (e.g., "Random Forest") for the title
#' @param save_path Where to save the PNG
plot_multiclass_roc <- function(roc_list, model_name, save_path) {
  
  # The ggroc function from pROC package handles lists of ROCs beautifully
  p <- ggroc(roc_list, size = 1) +
    theme_minimal() +
    ggtitle(paste("One-vs-Rest ROC Curves:", model_name)) +
    labs(x = "Specificity", y = "Sensitivity", color = "Cancer Class") +
    geom_abline(slope = 1, intercept = 1, linetype = "dashed", color = "darkgray") +
    theme(
      plot.title = element_text(hjust = 0.5, face = "bold"),
      legend.position = "bottom"
    )
  
  # Save the plot automatically
  ggsave(filename = save_path, plot = p, width = 8, height = 6, dpi = 300)
  
  message("✅ Saved ROC plot to ", save_path)
}